export const T = {
    LOGIN_USER: 'LOGIN_USER',
    REGISTER_USER: 'REGISTER_USER',
    AUTH_USER: 'AUTH_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    GET_PRODUCTS_BY_SELL: 'GET_PRODUCTS_BY_SELL',
    GET_PRODUCTS_BY_ARRIVAL: 'GET_PRODUCTS_BY_ARRIVAL',
    GET_BRANDS: 'GET_BRANDS',
    GET_ATTRIBUTE_NAME: 'GET_ATTRIBUTE_NAME',
    };
